# Generated by Django 3.1.7 on 2021-04-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_dayname_plan_recipeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
