# Generated by Django 3.1.7 on 2021-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_recipe_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='recipes',
            field=models.ManyToManyField(through='pages.RecipePlan', to='pages.Recipe'),
        ),
    ]
